package com.kaboom.eventbus.processor

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import java.io.OutputStream

class EventBusProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) : SymbolProcessor {

    private val collected = mutableListOf<Triple<String, String, String>>()

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val functions = resolver.getSymbolsWithAnnotation("com.kaboom.eventbus.SubscribeEvent")
            .filterIsInstance<KSFunctionDeclaration>()

        for (func in functions) {
            val parent = func.parentDeclaration as? KSClassDeclaration ?: continue
            val owner = parent.qualifiedName?.asString() ?: continue
            val funcName = func.simpleName.asString()

            val paramType = func.parameters.firstOrNull()
                ?.type?.resolve()?.declaration?.qualifiedName?.asString() ?: continue

            collected += Triple(owner, funcName, paramType)

            logger.info("KEventBus: Collected subscriber → $owner.$funcName($paramType)")
        }

        if (resolver.getNewFiles().none()) {
            generateRegistry()
        }

        return emptyList()
    }


    private fun generateRegistry() {
        if (collected.isEmpty()) return

        val pkg = "com.kaboom.eventbus.generated"
        val file = codeGenerator.createNewFile(
            Dependencies(false),
            pkg,
            "GeneratedEventBusRegistry"
        )

        val text = buildString {
            appendLine("// Auto-generated by KEventBus KSP Processor")
            appendLine("package $pkg")
            appendLine()
            appendLine("import kotlinx.coroutines.*")
            appendLine("import com.kaboom.eventbus.*")
            appendLine()
            appendLine("object GeneratedEventBusRegistry {")
            appendLine("    fun registerAll(scope: CoroutineScope? = null): List<Job> = listOf(")

            collected.forEachIndexed { index, (owner, func, param) ->
                val end = if (index == collected.lastIndex) "" else ","
                appendLine(
                    "        EventBus.on<$param>(scope) { ${owner}().$func(it) }$end"
                )
            }

            appendLine("    )")
            appendLine("}")
        }

        file.writeText(text)
        file.close()

        logger.info("KEventBus: Generated registry with ${collected.size} subscribers")
    }

    private fun OutputStream.writeText(str: String) {
        write(str.toByteArray())
    }
}

class EventBusProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        EventBusProcessor(environment.codeGenerator, environment.logger)
}
